import { NextResponse } from "next/server";

// Realistic Azadpur mandi price data (₹/quintal) — refreshed daily in production
// Based on Agmarknet seasonal patterns for North India, March 2026
const MANDI_DATA = [
  {
    commodity: "WATERMELON",
    emoji: "🍉",
    mandi: "Azadpur, Delhi",
    minPrice: 800,
    maxPrice: 1400,
    modalPrice: 950,
    unit: "₹/q",
    change: 15.2,
    sourceRegion: "Uttar Pradesh",
    arrivals: "2,840 q",
    riskScore: 84,
  },
  {
    commodity: "KASHMIR APPLE",
    emoji: "🍎",
    mandi: "Azadpur, Delhi",
    minPrice: 4800,
    maxPrice: 7500,
    modalPrice: 6200,
    unit: "₹/q",
    change: 8.4,
    sourceRegion: "J&K / Himachal",
    arrivals: "420 q",
    riskScore: 72,
  },
  {
    commodity: "KINNAUR APPLE",
    emoji: "🍎",
    mandi: "Azadpur, Delhi",
    minPrice: 5500,
    maxPrice: 9000,
    modalPrice: 7200,
    unit: "₹/q",
    change: 6.1,
    sourceRegion: "Kinnaur, HP",
    arrivals: "180 q",
    riskScore: 68,
  },
  {
    commodity: "ANAR",
    emoji: "🔴",
    mandi: "Azadpur, Delhi",
    minPrice: 3800,
    maxPrice: 6500,
    modalPrice: 4800,
    unit: "₹/q",
    change: -2.1,
    sourceRegion: "Solapur, Maharashtra",
    arrivals: "680 q",
    riskScore: 45,
  },
  {
    commodity: "KINNOW",
    emoji: "🍊",
    mandi: "Azadpur, Delhi",
    minPrice: 1600,
    maxPrice: 2800,
    modalPrice: 2100,
    unit: "₹/q",
    change: -7.8,
    sourceRegion: "Punjab",
    arrivals: "1,240 q",
    riskScore: 58,
  },
  {
    commodity: "ORANGE",
    emoji: "🟠",
    mandi: "Azadpur, Delhi",
    minPrice: 2000,
    maxPrice: 4200,
    modalPrice: 3100,
    unit: "₹/q",
    change: 3.2,
    sourceRegion: "Nagpur, Maharashtra",
    arrivals: "960 q",
    riskScore: 42,
  },
  {
    commodity: "SAFEDA MANGO",
    emoji: "🥭",
    mandi: "Azadpur, Delhi",
    minPrice: 3200,
    maxPrice: 6000,
    modalPrice: 4500,
    unit: "₹/q",
    change: 22.5,
    sourceRegion: "Malihabad, UP",
    arrivals: "180 q",
    riskScore: 35,
  },
  {
    commodity: "MAUSAMI",
    emoji: "🍋",
    mandi: "Azadpur, Delhi",
    minPrice: 1200,
    maxPrice: 2400,
    modalPrice: 1700,
    unit: "₹/q",
    change: -4.5,
    sourceRegion: "Nagpur, Maharashtra",
    arrivals: "1,580 q",
    riskScore: 38,
  },
  {
    commodity: "VNR GUAVA",
    emoji: "💚",
    mandi: "Azadpur, Delhi",
    minPrice: 1500,
    maxPrice: 2600,
    modalPrice: 1900,
    unit: "₹/q",
    change: 1.8,
    sourceRegion: "Prayagraj, UP",
    arrivals: "740 q",
    riskScore: 29,
  },
  {
    commodity: "GRAPES",
    emoji: "🍇",
    mandi: "Azadpur, Delhi",
    minPrice: 4000,
    maxPrice: 8500,
    modalPrice: 5800,
    unit: "₹/q",
    change: -12.3,
    sourceRegion: "Nashik, Maharashtra",
    arrivals: "820 q",
    riskScore: 62,
  },
];

export async function GET() {
  // In production, this would call Agmarknet or data.gov.in API
  return NextResponse.json({
    data: MANDI_DATA,
    source: "Agmarknet (Simulated)",
    asOf: new Date().toISOString(),
    market: "Azadpur Mandi, Delhi",
  });
}
