// Retailer profiles — real names from order data
// Scores, tiers, credit, payment terms are AI-derived estimates from order history
// SKU allocations are computed from actual order quantities

export interface RetailerProfile {
  name: string;
  area: string;
  tier: "Priority" | "Secondary" | "Low Value";
  score: number;
  paymentDays: number;
  creditScore: number;
  avgDailyKg: number;
  shopType: string;
  color: string; // accent color per retailer
  radarMetrics: { label: string; value: number }[];
  skuAllocation: Record<string, number>; // SKU → % of their order (real data)
}

export const retailerProfiles: RetailerProfile[] = [
  {
    name: "RAJKUMAR FRUIT VASANT VIHAR",
    area: "Vasant Vihar, South Delhi",
    tier: "Priority",
    score: 96,
    paymentDays: 7,
    creditScore: 94,
    avgDailyKg: 280,
    shopType: "Premium Retail",
    color: "#16a34a",
    radarMetrics: [
      { label: "Volume", value: 96 }, { label: "Payment", value: 98 },
      { label: "Consistency", value: 94 }, { label: "Growth", value: 90 }, { label: "Location", value: 99 },
    ],
    skuAllocation: { WATERMELON: 32, ORANGE: 20, "KASHMIR APPLE": 18, ANAR: 16, MAUSAMI: 14 },
  },
  {
    name: "RAHUL FRUIT 1 VASANT VIHAR",
    area: "Vasant Vihar, South Delhi",
    tier: "Priority",
    score: 93,
    paymentDays: 7,
    creditScore: 91,
    avgDailyKg: 245,
    shopType: "Premium Retail",
    color: "#16a34a",
    radarMetrics: [
      { label: "Volume", value: 92 }, { label: "Payment", value: 96 },
      { label: "Consistency", value: 93 }, { label: "Growth", value: 88 }, { label: "Location", value: 98 },
    ],
    skuAllocation: { WATERMELON: 34, "KASHMIR APPLE": 21, "TURKEY APPLE": 16, ANAR: 15, PAPAYA: 14 },
  },
  {
    name: "DEEPAK FRUIT GURGAON SEC 69",
    area: "Sector 69, Gurgaon",
    tier: "Priority",
    score: 91,
    paymentDays: 10,
    creditScore: 88,
    avgDailyKg: 230,
    shopType: "Wholesale + Retail",
    color: "#0d9488",
    radarMetrics: [
      { label: "Volume", value: 90 }, { label: "Payment", value: 88 },
      { label: "Consistency", value: 92 }, { label: "Growth", value: 95 }, { label: "Location", value: 87 },
    ],
    skuAllocation: { WATERMELON: 28, "KASHMIR APPLE": 23, ANAR: 19, ORANGE: 15, "KINNAUR APPLE": 15 },
  },
  {
    name: "KISHAN FRUIT GURGAON SEC-69",
    area: "Sector 69, Gurgaon",
    tier: "Priority",
    score: 89,
    paymentDays: 10,
    creditScore: 86,
    avgDailyKg: 218,
    shopType: "Wholesale",
    color: "#0d9488",
    radarMetrics: [
      { label: "Volume", value: 88 }, { label: "Payment", value: 86 },
      { label: "Consistency", value: 90 }, { label: "Growth", value: 92 }, { label: "Location", value: 86 },
    ],
    skuAllocation: { WATERMELON: 30, "KASHMIR APPLE": 23, "KINNAUR APPLE": 18, ANAR: 17, "SHIMLA APPLE": 12 },
  },
  {
    name: "RANVEER FRUITS INA",
    area: "INA Market, New Delhi",
    tier: "Priority",
    score: 88,
    paymentDays: 12,
    creditScore: 84,
    avgDailyKg: 204,
    shopType: "Market Stall",
    color: "#16a34a",
    radarMetrics: [
      { label: "Volume", value: 86 }, { label: "Payment", value: 84 },
      { label: "Consistency", value: 90 }, { label: "Growth", value: 88 }, { label: "Location", value: 94 },
    ],
    skuAllocation: { WATERMELON: 29, ORANGE: 19, ANAR: 18, "KASHMIR APPLE": 18, "KINNAUR APPLE": 16 },
  },
  {
    name: "SANAWAR FRUIT GURGAON SEC-69",
    area: "Sector 69, Gurgaon",
    tier: "Priority",
    score: 87,
    paymentDays: 12,
    creditScore: 83,
    avgDailyKg: 203,
    shopType: "Wholesale",
    color: "#0d9488",
    radarMetrics: [
      { label: "Volume", value: 86 }, { label: "Payment", value: 82 },
      { label: "Consistency", value: 89 }, { label: "Growth", value: 90 }, { label: "Location", value: 86 },
    ],
    skuAllocation: { WATERMELON: 28, ORANGE: 20, ANAR: 18, "KASHMIR APPLE": 18, "KINNAUR APPLE": 16 },
  },
  {
    name: "SONU FRUIT CHHATARPUR",
    area: "Chhatarpur, South Delhi",
    tier: "Priority",
    score: 85,
    paymentDays: 14,
    creditScore: 82,
    avgDailyKg: 198,
    shopType: "Retail Shop",
    color: "#7c3aed",
    radarMetrics: [
      { label: "Volume", value: 84 }, { label: "Payment", value: 82 },
      { label: "Consistency", value: 88 }, { label: "Growth", value: 85 }, { label: "Location", value: 84 },
    ],
    skuAllocation: { WATERMELON: 25, "KASHMIR APPLE": 23, ANAR: 20, ORANGE: 17, "KINNAUR APPLE": 15 },
  },
  {
    name: "KISHAN MANDI GURGAON",
    area: "Gurgaon Mandi",
    tier: "Priority",
    score: 84,
    paymentDays: 14,
    creditScore: 80,
    avgDailyKg: 195,
    shopType: "Mandi Wholesale",
    color: "#0d9488",
    radarMetrics: [
      { label: "Volume", value: 88 }, { label: "Payment", value: 78 },
      { label: "Consistency", value: 85 }, { label: "Growth", value: 82 }, { label: "Location", value: 80 },
    ],
    skuAllocation: { WATERMELON: 27, "KINNAUR APPLE": 21, ANAR: 20, "KASHMIR APPLE": 19, ORANGE: 13 },
  },
  {
    name: "YADUVANSHI FRUITS VAISHALI",
    area: "Vaishali, Ghaziabad",
    tier: "Priority",
    score: 83,
    paymentDays: 14,
    creditScore: 80,
    avgDailyKg: 190,
    shopType: "Retail Chain",
    color: "#dc2626",
    radarMetrics: [
      { label: "Volume", value: 82 }, { label: "Payment", value: 80 },
      { label: "Consistency", value: 86 }, { label: "Growth", value: 88 }, { label: "Location", value: 78 },
    ],
    skuAllocation: { WATERMELON: 26, ORANGE: 20, "KASHMIR APPLE": 20, ANAR: 17, "KINNAUR APPLE": 17 },
  },
  {
    name: "BALA JI SEC 25",
    area: "Sector 25, Gurgaon",
    tier: "Priority",
    score: 82,
    paymentDays: 15,
    creditScore: 79,
    avgDailyKg: 181,
    shopType: "Retail Shop",
    color: "#0891b2",
    radarMetrics: [
      { label: "Volume", value: 80 }, { label: "Payment", value: 78 },
      { label: "Consistency", value: 84 }, { label: "Growth", value: 84 }, { label: "Location", value: 82 },
    ],
    skuAllocation: { WATERMELON: 31, "KASHMIR APPLE": 19, ORANGE: 19, ANAR: 18, "KINNAUR APPLE": 13 },
  },
  {
    name: "RAHUL FRUITS GOVINDPURI",
    area: "Govindpuri, South Delhi",
    tier: "Secondary",
    score: 78,
    paymentDays: 18,
    creditScore: 75,
    avgDailyKg: 178,
    shopType: "Kirana + Fruits",
    color: "#7c3aed",
    radarMetrics: [
      { label: "Volume", value: 78 }, { label: "Payment", value: 72 },
      { label: "Consistency", value: 80 }, { label: "Growth", value: 82 }, { label: "Location", value: 78 },
    ],
    skuAllocation: { WATERMELON: 29, "KINNAUR APPLE": 23, ANAR: 19, "KASHMIR APPLE": 17, ORANGE: 12 },
  },
  {
    name: "UMESH FRUIT SHREE RAM MARKET",
    area: "Shree Ram Market, Delhi",
    tier: "Secondary",
    score: 76,
    paymentDays: 18,
    creditScore: 73,
    avgDailyKg: 177,
    shopType: "Market Stall",
    color: "#16a34a",
    radarMetrics: [
      { label: "Volume", value: 76 }, { label: "Payment", value: 70 },
      { label: "Consistency", value: 78 }, { label: "Growth", value: 78 }, { label: "Location", value: 76 },
    ],
    skuAllocation: { WATERMELON: 29, ORANGE: 20, ANAR: 19, "KASHMIR APPLE": 18, "KINNAUR APPLE": 14 },
  },
  {
    name: "TIP TOP FRUIT SHOP NOIDA SEC 93",
    area: "Sector 93, Noida",
    tier: "Secondary",
    score: 75,
    paymentDays: 20,
    creditScore: 72,
    avgDailyKg: 177,
    shopType: "Retail Shop",
    color: "#dc2626",
    radarMetrics: [
      { label: "Volume", value: 78 }, { label: "Payment", value: 68 },
      { label: "Consistency", value: 76 }, { label: "Growth", value: 80 }, { label: "Location", value: 72 },
    ],
    skuAllocation: { WATERMELON: 34, "KINNAUR APPLE": 20, "KASHMIR APPLE": 19, ANAR: 15, ORANGE: 12 },
  },
  {
    name: "SURAJ FRUIT FATEHPUR BERI",
    area: "Fatehpur Beri, South Delhi",
    tier: "Secondary",
    score: 74,
    paymentDays: 21,
    creditScore: 71,
    avgDailyKg: 176,
    shopType: "Wholesale",
    color: "#d97706",
    radarMetrics: [
      { label: "Volume", value: 80 }, { label: "Payment", value: 66 },
      { label: "Consistency", value: 74 }, { label: "Growth", value: 76 }, { label: "Location", value: 72 },
    ],
    skuAllocation: { WATERMELON: 32, "KINNAUR APPLE": 20, "KASHMIR APPLE": 20, ORANGE: 17, ANAR: 11 },
  },
  {
    name: "ARIF FRUIT CHHATARPUR",
    area: "Chhatarpur, South Delhi",
    tier: "Secondary",
    score: 73,
    paymentDays: 21,
    creditScore: 70,
    avgDailyKg: 175,
    shopType: "Retail Shop",
    color: "#7c3aed",
    radarMetrics: [
      { label: "Volume", value: 76 }, { label: "Payment", value: 65 },
      { label: "Consistency", value: 74 }, { label: "Growth", value: 74 }, { label: "Location", value: 76 },
    ],
    skuAllocation: { WATERMELON: 27, "KINNAUR APPLE": 24, "KASHMIR APPLE": 21, ANAR: 15, ORANGE: 13 },
  },
  {
    name: "MANGALAM FRUITS HUAZ KHAS",
    area: "Hauz Khas, South Delhi",
    tier: "Secondary",
    score: 72,
    paymentDays: 21,
    creditScore: 69,
    avgDailyKg: 174,
    shopType: "Premium Retail",
    color: "#16a34a",
    radarMetrics: [
      { label: "Volume", value: 74 }, { label: "Payment", value: 66 },
      { label: "Consistency", value: 73 }, { label: "Growth", value: 76 }, { label: "Location", value: 80 },
    ],
    skuAllocation: { WATERMELON: 24, "KASHMIR APPLE": 23, "KINNAUR APPLE": 23, ANAR: 18, ORANGE: 12 },
  },
  {
    name: "SUNIL FRUIT SEC 49",
    area: "Sector 49, Gurgaon",
    tier: "Secondary",
    score: 71,
    paymentDays: 22,
    creditScore: 68,
    avgDailyKg: 171,
    shopType: "Retail Shop",
    color: "#0d9488",
    radarMetrics: [
      { label: "Volume", value: 72 }, { label: "Payment", value: 64 },
      { label: "Consistency", value: 73 }, { label: "Growth", value: 74 }, { label: "Location", value: 74 },
    ],
    skuAllocation: { WATERMELON: 32, "KASHMIR APPLE": 18, ORANGE: 18, "KINNAUR APPLE": 16, ANAR: 16 },
  },
  {
    name: "NETAJI FRUIT HAUZ KHAS",
    area: "Hauz Khas, South Delhi",
    tier: "Secondary",
    score: 70,
    paymentDays: 22,
    creditScore: 67,
    avgDailyKg: 169,
    shopType: "Market Stall",
    color: "#16a34a",
    radarMetrics: [
      { label: "Volume", value: 72 }, { label: "Payment", value: 63 },
      { label: "Consistency", value: 72 }, { label: "Growth", value: 73 }, { label: "Location", value: 80 },
    ],
    skuAllocation: { WATERMELON: 33, "KINNAUR APPLE": 20, ANAR: 20, "KASHMIR APPLE": 14, ORANGE: 13 },
  },
  {
    name: "PAPPU FRUIT 4 SEC-50",
    area: "Sector 50, Gurgaon",
    tier: "Secondary",
    score: 69,
    paymentDays: 25,
    creditScore: 65,
    avgDailyKg: 168,
    shopType: "Retail Shop",
    color: "#0d9488",
    radarMetrics: [
      { label: "Volume", value: 70 }, { label: "Payment", value: 60 },
      { label: "Consistency", value: 71 }, { label: "Growth", value: 72 }, { label: "Location", value: 72 },
    ],
    skuAllocation: { WATERMELON: 29, "KASHMIR APPLE": 24, "KINNAUR APPLE": 18, ANAR: 17, "SAFEDA MANGO": 12 },
  },
  {
    name: "SANJEEV SAXENA FRUIT KALKA JI",
    area: "Kalkaji, South Delhi",
    tier: "Secondary",
    score: 68,
    paymentDays: 25,
    creditScore: 64,
    avgDailyKg: 168,
    shopType: "Retail Shop",
    color: "#7c3aed",
    radarMetrics: [
      { label: "Volume", value: 70 }, { label: "Payment", value: 60 },
      { label: "Consistency", value: 70 }, { label: "Growth", value: 70 }, { label: "Location", value: 72 },
    ],
    skuAllocation: { WATERMELON: 34, "KINNAUR APPLE": 20, "KASHMIR APPLE": 18, ANAR: 16, ORANGE: 12 },
  },
];
