// Full retailer profiles — real names from order data, enriched with scoring + vendor allocation

export interface RetailerProfile {
  name: string;
  area: string;
  tier: "Priority" | "Secondary" | "Low Value";
  score: number;
  paymentDays: number;
  creditScore: number;
  avgDailyKg: number;
  shopType: string;
  vendor: string;
  vendorColor: string;
  radarMetrics: { label: string; value: number }[];
  skuAllocation: Record<string, number>; // SKU → % of their order
}

export const retailerProfiles: RetailerProfile[] = [
  {
    name: "RAJKUMAR FRUIT VASANT VIHAR",
    area: "Vasant Vihar, South Delhi",
    tier: "Priority",
    score: 96,
    paymentDays: 7,
    creditScore: 94,
    avgDailyKg: 280,
    shopType: "Premium Retail",
    vendor: "Agri Fresh Co.",
    vendorColor: "#16a34a",
    radarMetrics: [
      { label: "Volume", value: 96 },
      { label: "Payment", value: 98 },
      { label: "Consistency", value: 94 },
      { label: "Growth", value: 90 },
      { label: "Location", value: 99 },
    ],
    skuAllocation: { WATERMELON: 38, "KASHMIR APPLE": 21, ORANGE: 18, ANAR: 15, KINNOW: 8 },
  },
  {
    name: "RAHUL FRUIT 1 VASANT VIHAR",
    area: "Vasant Vihar, South Delhi",
    tier: "Priority",
    score: 93,
    paymentDays: 7,
    creditScore: 91,
    avgDailyKg: 245,
    shopType: "Premium Retail",
    vendor: "Agri Fresh Co.",
    vendorColor: "#16a34a",
    radarMetrics: [
      { label: "Volume", value: 92 },
      { label: "Payment", value: 96 },
      { label: "Consistency", value: 93 },
      { label: "Growth", value: 88 },
      { label: "Location", value: 98 },
    ],
    skuAllocation: { WATERMELON: 40, "KASHMIR APPLE": 24, "TURKEY APPLE": 20, ANAR: 16 },
  },
  {
    name: "DEEPAK FRUIT GURGAON SEC 69",
    area: "Sector 69, Gurgaon",
    tier: "Priority",
    score: 91,
    paymentDays: 10,
    creditScore: 88,
    avgDailyKg: 230,
    shopType: "Wholesale + Retail",
    vendor: "Deccan Produce",
    vendorColor: "#f97316",
    radarMetrics: [
      { label: "Volume", value: 90 },
      { label: "Payment", value: 88 },
      { label: "Consistency", value: 92 },
      { label: "Growth", value: 95 },
      { label: "Location", value: 87 },
    ],
    skuAllocation: { WATERMELON: 35, "KASHMIR APPLE": 27, ANAR: 22, "KINNAUR APPLE": 16 },
  },
  {
    name: "KISHAN FRUIT GURGAON SEC-69",
    area: "Sector 69, Gurgaon",
    tier: "Priority",
    score: 89,
    paymentDays: 10,
    creditScore: 86,
    avgDailyKg: 218,
    shopType: "Wholesale",
    vendor: "Deccan Produce",
    vendorColor: "#f97316",
    radarMetrics: [
      { label: "Volume", value: 88 },
      { label: "Payment", value: 86 },
      { label: "Consistency", value: 90 },
      { label: "Growth", value: 92 },
      { label: "Location", value: 86 },
    ],
    skuAllocation: { WATERMELON: 37, "KASHMIR APPLE": 27, "KINNAUR APPLE": 21, ANAR: 15 },
  },
  {
    name: "RANVEER FRUITS INA",
    area: "INA Market, New Delhi",
    tier: "Priority",
    score: 88,
    paymentDays: 12,
    creditScore: 84,
    avgDailyKg: 204,
    shopType: "Market Stall",
    vendor: "Green Valley Farms",
    vendorColor: "#22c55e",
    radarMetrics: [
      { label: "Volume", value: 86 },
      { label: "Payment", value: 84 },
      { label: "Consistency", value: 90 },
      { label: "Growth", value: 88 },
      { label: "Location", value: 94 },
    ],
    skuAllocation: { WATERMELON: 33, ORANGE: 22, ANAR: 20, "KASHMIR APPLE": 25 },
  },
  {
    name: "SANAWAR FRUIT GURGAON SEC-69",
    area: "Sector 69, Gurgaon",
    tier: "Priority",
    score: 87,
    paymentDays: 12,
    creditScore: 83,
    avgDailyKg: 203,
    shopType: "Wholesale",
    vendor: "Deccan Produce",
    vendorColor: "#f97316",
    radarMetrics: [
      { label: "Volume", value: 86 },
      { label: "Payment", value: 82 },
      { label: "Consistency", value: 89 },
      { label: "Growth", value: 90 },
      { label: "Location", value: 86 },
    ],
    skuAllocation: { WATERMELON: 34, ORANGE: 22, ANAR: 20, "KASHMIR APPLE": 24 },
  },
  {
    name: "SONU FRUIT CHHATARPUR",
    area: "Chhatarpur, South Delhi",
    tier: "Priority",
    score: 85,
    paymentDays: 14,
    creditScore: 82,
    avgDailyKg: 198,
    shopType: "Retail Shop",
    vendor: "Southern Harvest",
    vendorColor: "#8b5cf6",
    radarMetrics: [
      { label: "Volume", value: 84 },
      { label: "Payment", value: 82 },
      { label: "Consistency", value: 88 },
      { label: "Growth", value: 85 },
      { label: "Location", value: 84 },
    ],
    skuAllocation: { WATERMELON: 26, "KASHMIR APPLE": 23, ANAR: 20, "KINNAUR APPLE": 18, KINNOW: 13 },
  },
  {
    name: "KISHAN MANDI GURGAON",
    area: "Gurgaon Mandi",
    tier: "Priority",
    score: 84,
    paymentDays: 14,
    creditScore: 80,
    avgDailyKg: 195,
    shopType: "Mandi Wholesale",
    vendor: "Indo Farm Supply",
    vendorColor: "#f59e0b",
    radarMetrics: [
      { label: "Volume", value: 88 },
      { label: "Payment", value: 78 },
      { label: "Consistency", value: 85 },
      { label: "Growth", value: 82 },
      { label: "Location", value: 80 },
    ],
    skuAllocation: { WATERMELON: 30, "KINNAUR APPLE": 22, ANAR: 21, "KASHMIR APPLE": 18, KINNOW: 9 },
  },
  {
    name: "YADUVANSHI FRUITS VAISHALI",
    area: "Vaishali, Ghaziabad",
    tier: "Priority",
    score: 83,
    paymentDays: 14,
    creditScore: 80,
    avgDailyKg: 190,
    shopType: "Retail Chain",
    vendor: "Eastern Growers",
    vendorColor: "#ef4444",
    radarMetrics: [
      { label: "Volume", value: 82 },
      { label: "Payment", value: 80 },
      { label: "Consistency", value: 86 },
      { label: "Growth", value: 88 },
      { label: "Location", value: 78 },
    ],
    skuAllocation: { WATERMELON: 32, ORANGE: 23, "KASHMIR APPLE": 22, ANAR: 14, KINNOW: 9 },
  },
  {
    name: "BALA JI SEC 25",
    area: "Sector 25, Gurgaon",
    tier: "Priority",
    score: 82,
    paymentDays: 15,
    creditScore: 79,
    avgDailyKg: 181,
    shopType: "Retail Shop",
    vendor: "Coastal Agri",
    vendorColor: "#06b6d4",
    radarMetrics: [
      { label: "Volume", value: 80 },
      { label: "Payment", value: 78 },
      { label: "Consistency", value: 84 },
      { label: "Growth", value: 84 },
      { label: "Location", value: 82 },
    ],
    skuAllocation: { WATERMELON: 36, "KASHMIR APPLE": 20, ORANGE: 21, ANAR: 14, KINNOW: 9 },
  },
  {
    name: "RAHUL FRUITS GOVINDPURI",
    area: "Govindpuri, South Delhi",
    tier: "Secondary",
    score: 78,
    paymentDays: 18,
    creditScore: 75,
    avgDailyKg: 178,
    shopType: "Kirana + Fruits",
    vendor: "Southern Harvest",
    vendorColor: "#8b5cf6",
    radarMetrics: [
      { label: "Volume", value: 78 },
      { label: "Payment", value: 72 },
      { label: "Consistency", value: 80 },
      { label: "Growth", value: 82 },
      { label: "Location", value: 78 },
    ],
    skuAllocation: { WATERMELON: 32, "KINNAUR APPLE": 25, ANAR: 21, "KASHMIR APPLE": 22 },
  },
  {
    name: "UMESH FRUIT SHREE RAM MARKET",
    area: "Shree Ram Market, Delhi",
    tier: "Secondary",
    score: 76,
    paymentDays: 18,
    creditScore: 73,
    avgDailyKg: 177,
    shopType: "Market Stall",
    vendor: "Green Valley Farms",
    vendorColor: "#22c55e",
    radarMetrics: [
      { label: "Volume", value: 76 },
      { label: "Payment", value: 70 },
      { label: "Consistency", value: 78 },
      { label: "Growth", value: 78 },
      { label: "Location", value: 76 },
    ],
    skuAllocation: { WATERMELON: 32, ORANGE: 21, ANAR: 20, "KASHMIR APPLE": 18, KINNOW: 9 },
  },
  {
    name: "TIP TOP FRUIT SHOP NOIDA SEC 93",
    area: "Sector 93, Noida",
    tier: "Secondary",
    score: 75,
    paymentDays: 20,
    creditScore: 72,
    avgDailyKg: 177,
    shopType: "Retail Shop",
    vendor: "Eastern Growers",
    vendorColor: "#ef4444",
    radarMetrics: [
      { label: "Volume", value: 78 },
      { label: "Payment", value: 68 },
      { label: "Consistency", value: 76 },
      { label: "Growth", value: 80 },
      { label: "Location", value: 72 },
    ],
    skuAllocation: { WATERMELON: 36, "KINNAUR APPLE": 21, "KASHMIR APPLE": 20, ANAR: 14, KINNOW: 9 },
  },
  {
    name: "SURAJ FRUIT FATEHPUR BERI",
    area: "Fatehpur Beri, South Delhi",
    tier: "Secondary",
    score: 74,
    paymentDays: 21,
    creditScore: 71,
    avgDailyKg: 176,
    shopType: "Wholesale",
    vendor: "Indo Farm Supply",
    vendorColor: "#f59e0b",
    radarMetrics: [
      { label: "Volume", value: 80 },
      { label: "Payment", value: 66 },
      { label: "Consistency", value: 74 },
      { label: "Growth", value: 76 },
      { label: "Location", value: 72 },
    ],
    skuAllocation: { WATERMELON: 38, "KINNAUR APPLE": 24, "KASHMIR APPLE": 24, ANAR: 14 },
  },
  {
    name: "ARIF FRUIT CHHATARPUR",
    area: "Chhatarpur, South Delhi",
    tier: "Secondary",
    score: 73,
    paymentDays: 21,
    creditScore: 70,
    avgDailyKg: 175,
    shopType: "Retail Shop",
    vendor: "Southern Harvest",
    vendorColor: "#8b5cf6",
    radarMetrics: [
      { label: "Volume", value: 76 },
      { label: "Payment", value: 65 },
      { label: "Consistency", value: 74 },
      { label: "Growth", value: 74 },
      { label: "Location", value: 76 },
    ],
    skuAllocation: { WATERMELON: 30, "KINNAUR APPLE": 26, "KASHMIR APPLE": 22, ANAR: 22 },
  },
];

// Vendor details
export interface VendorDetail {
  name: string;
  location: string;
  reliability: number;
  color: string;
  topSkus: string[];
  paymentTerms: string;
  leadTimeDays: number;
}

export const vendorDetails: Record<string, VendorDetail> = {
  "Agri Fresh Co.": {
    name: "Agri Fresh Co.",
    location: "Nashik, Maharashtra",
    reliability: 96,
    color: "#16a34a",
    topSkus: ["WATERMELON", "KASHMIR APPLE", "SHIMLA APPLE"],
    paymentTerms: "Net 5 days",
    leadTimeDays: 1,
  },
  "Green Valley Farms": {
    name: "Green Valley Farms",
    location: "Ratnagiri, Maharashtra",
    reliability: 93,
    color: "#22c55e",
    topSkus: ["ORANGE", "SAFEDA MANGO", "KINNOW"],
    paymentTerms: "Net 7 days",
    leadTimeDays: 2,
  },
  "Deccan Produce": {
    name: "Deccan Produce",
    location: "Pune, Maharashtra",
    reliability: 90,
    color: "#f97316",
    topSkus: ["WATERMELON", "KASHMIR APPLE", "ANAR"],
    paymentTerms: "Net 7 days",
    leadTimeDays: 1,
  },
  "Southern Harvest": {
    name: "Southern Harvest",
    location: "Mysore, Karnataka",
    reliability: 88,
    color: "#8b5cf6",
    topSkus: ["VNR GUAVA", "PAPAYA", "KINNAUR APPLE"],
    paymentTerms: "Net 10 days",
    leadTimeDays: 2,
  },
  "Indo Farm Supply": {
    name: "Indo Farm Supply",
    location: "Nagpur, Maharashtra",
    reliability: 85,
    color: "#f59e0b",
    topSkus: ["WATERMELON", "KINNAUR APPLE", "ANAR"],
    paymentTerms: "Net 10 days",
    leadTimeDays: 2,
  },
  "Coastal Agri": {
    name: "Coastal Agri",
    location: "Goa",
    reliability: 82,
    color: "#06b6d4",
    topSkus: ["KINNOW", "ORANGE", "WATERMELON"],
    paymentTerms: "Net 14 days",
    leadTimeDays: 3,
  },
  "Eastern Growers": {
    name: "Eastern Growers",
    location: "Kolkata, West Bengal",
    reliability: 75,
    color: "#ef4444",
    topSkus: ["KASHMIR APPLE", "KINNAUR APPLE", "WATERMELON"],
    paymentTerms: "Net 14 days",
    leadTimeDays: 3,
  },
};
